"""baseline

Revision ID: 4b4d295677d1
Revises: 
Create Date: 2026-02-17 14:49:23.005561

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4b4d295677d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_queue', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job_queue', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_queue', type_='foreignkey')
    op.drop_column('job_queue', 'project_id')
    # ### end Alembic commands ###

