"""create findings table

Revision ID: f604b560c614
Revises: 4b4d295677d1
Create Date: 2026-02-17 16:22:12.485210

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f604b560c614'
down_revision = '4b4d295677d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'findings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('severity', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('affected_items', sa.JSON(), nullable=True),
        sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('related_submittal_id', sa.String(), nullable=True),
        sa.Column('related_rfi_id', sa.String(), nullable=True),
        sa.Column('related_inspection_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    # Primary keys are indexed automatically in Postgres; no separate ix_findings_id needed.
    op.create_index(op.f('ix_findings_project_id'), 'findings', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_project_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###

